name: Birthday Alerts
on:
  schedule:
    - cron: '0 10 * * *'  # 10 AM UTC
    - cron: '0 18 * * *'  # 6 PM UTC
    - cron: '0 23 * * *'  # 11 PM UTC
  workflow_dispatch:  # Manual trigger for testing

jobs:
  send-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install python-telegram-bot==13.7  # Specify version to avoid conflicts
      - name: Run alerts
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python birthday_alerts.py
